### ISSUE TITLE
Rewrite module reopen_updated.rb

### ISSUE THREAD

**Issue by Synchunk** [Mojira/Arisa#13]

**Comment by Synchunk** [comment]
Actually, I'm not sure if this is a good idea.
Should the bot automatically reopen issues that are resolved as "Awaiting response" when they're updated? That would also include comments being posted by people other than the reporter, CHK updates, comment edits and so on.

**Comment by Tora-B** [comment]
Even if it is the reporter making an update, that's not a guarantee that they've adequately responded. For example, we might ask them for a crash report, and instead of providing one, they may do something else, like update the affected versions.

That still doesn't leave us with a good way of finding issues that need to be reopened, which I'm guessing was the original motivation for the module, since JIRA's query engine [doesn't support comparing fields with each other](https://jira.atlassian.com/browse/JRA-20727) without a plugin.

**Comment by ezfe** [comment]
We really need a queue system to manage tickets

**Comment by Synchunk** [comment]
Rewrote the module, feel free to disable it in `config/modules.rb` if it does more harm than good.
